// examples-react/src/pages/components/toast/default.tsx
import { useState } from "react"
import { Button } from "@/components/button"
import { Title } from "@/components/title"
import { Text } from "@/components/text"
import { Toast, ToastContent } from "@/components/toast"
import { Toaster } from "@/components/toaster"

export function Example() {
    const [toasts, setToasts] = useState<number[]>([])

    const showToast = () => {
        setToasts(current => [...current, Date.now()])
    }

    const closeToast = (toast: number) => {
        setToasts(current => current.filter(item => item !== toast))
    }

    return (
        <>
            <Button onClick={showToast}>Show toast</Button>

            <Toaster className="items-end">
                {toasts.map((toast) => (
                    <Toast key={toast} onClose={() => closeToast(toast)}>
                        {({ close }) => (
                            <ToastContent>
                                <div className="flex-col">
                                    <Title>Hello toast</Title>
                                    <Text>Amazing toast</Text>
                                </div>
                                <Button className="muted ml-auto" onClick={close}>Close</Button>
                            </ToastContent>
                        )}
                    </Toast>
                ))}
            </Toaster>
        </>
    )
}

// examples-vue/src/pages/components/toast/default.vue
<script setup lang="ts">
    import { ref } from 'vue'
    import { Button } from '@/components/button'
    import { Title } from '@/components/title'
    import { Text } from '@/components/text'
    import { Toast, ToastContent } from '@/components/toast'
    import { Toaster } from '@/components/toaster'

    const toasts = ref<number[]>([])

    const showToast = () => {
        toasts.value.push(Date.now())
    }

    const closeToast = (toast: number) => {
        toasts.value = toasts.value.filter(item => item !== toast)
    }
</script>

<template>
    <Button @click="showToast">Show toast</Button>

    <Toaster class="items-end">
        <Toast v-for="toast in toasts" v-slot="{ close }" :key="toast" @close="closeToast(toast)">
            <ToastContent>
                <div class="flex-col">
                    <Title>Hello toast</Title>
                    <Text>Amazing toast</Text>
                </div>
                <Button class="muted ml-auto" @click="close">Close</Button>
            </ToastContent>
        </Toast>
    </Toaster>
</template>
