// examples-react/src/pages/components/popover/interest.tsx
import { useId } from 'react'
import { Button } from '@/components/button'
import { Popover, PopoverContent } from '@/components/popover'

export function Example() {
    const popoverInterest = useId()

    return (
        <>
            <Button interestfor={popoverInterest}>Popover</Button>
            <Popover className="bottom my-2" popover="hint" id={popoverInterest}>
                <PopoverContent className="shadow dark:bg-body-secondary p-2 w-32 flex flex-col">
                    <Button className="ghosted accent-main justify-start w-full">Item 1</Button>
                    <Button className="ghosted accent-main justify-start w-full">Item 2</Button>
                </PopoverContent>
            </Popover>
        </>
    )
}

// examples-vue/src/pages/components/popover/interest.vue
<script setup lang="ts">
    import { useId } from 'vue'
    import { Button } from '@/components/button'
    import { Popover, PopoverContent } from '@/components/popover'

    const popoverInterest = useId()
</script>

<template>
    <Button :interestfor="popoverInterest">Popover</Button>
    <Popover class="bottom my-2" popover="hint" :id="popoverInterest">
        <PopoverContent class="shadow dark:bg-body-secondary p-2 w-32 flex flex-col">
            <Button class="ghosted accent-main justify-start w-full">Item 1</Button>
            <Button class="ghosted accent-main justify-start w-full">Item 2</Button>
        </PopoverContent>
    </Popover>
</template>
