// examples-react/src/pages/components/popover/tooltip.tsx
import { type CSSProperties, useId } from 'react'
import { Button } from '@/components/button'
import { Popover, PopoverContent } from '@/components/popover'

export function Example() {
    const tooltipPopover = useId()

    return (
        <>
            <Button interestfor={tooltipPopover} style={{ interestDelay: '0s' } as CSSProperties}>
                Tooltip
            </Button>
            <Popover className="tooltip bottom my-1" id={tooltipPopover} popover="hint" placement="bottom">
                <PopoverContent>
                    Popover
                </PopoverContent>
            </Popover>
        </>
    )
}

// examples-vue/src/pages/components/popover/tooltip.vue
<script setup lang="ts">
    import { useId } from 'vue'
    import { Button } from '@/components/button'
    import { Popover, PopoverContent } from '@/components/popover'

    const tooltipPopover = useId()
</script>

<template>
    <Button :interestfor="tooltipPopover" style="interest-delay: 0s;">
        Tooltip
    </Button>
    <Popover class="tooltip bottom my-1" :id="tooltipPopover" popover="hint" placement="bottom">
        <PopoverContent>
            Popover
        </PopoverContent>
    </Popover>
</template>
