// examples-react/src/pages/components/dialog/basic.tsx
import { useId } from 'react'
import { Button } from '@/components/button'
import { Dialog, DialogContent } from '@/components/dialog'
import { Heading } from '@/components/heading'

export function Example() {
    const dialogBasic = useId()

    return (
        <>
            <Button command="show-modal" commandfor={dialogBasic}>
                Open Dialog
            </Button>
            <Dialog id={dialogBasic}>
                <DialogContent>
                    <Heading>Hello there!</Heading>
                    <Button className="muted accent-main" command="close" commandfor={dialogBasic}>
                        Close me!
                    </Button>
                </DialogContent>
            </Dialog>
        </>
    )
}

// examples-vue/src/pages/components/dialog/basic.vue
<script setup lang="ts">
    import { useId } from 'vue'
    import { Button } from '@/components/button'
    import { Dialog, DialogContent } from '@/components/dialog'
    import { Heading } from '@/components/heading'

    const dialogBasic = useId()
</script>

<template>
    <Button command="show-modal" :commandfor="dialogBasic">
        Open Dialog
    </Button>
    <Dialog :id="dialogBasic" closedby="any">
        <DialogContent>
            <Heading>Hello there!</Heading>
            <Button class="muted accent-main" command="close" :commandfor="dialogBasic">
                Close me!
            </Button>
        </DialogContent>
    </Dialog>
</template>
